### ISSUE TITLE
new section clients 

### ISSUE THREAD

**Issue by andredurazzo** [octotech-digital/octotech#3]
criar seção de clientes

**Comment by rafael-octotech** [comment]
Tive problemas na hora de dar o push, esqueci de alterar meu usuário pro projeto, to com meu usuário da outra empresa.

<img width="861" alt="captura de tela 2019-03-02 as 01 16 05" src="https://user-images.githubusercontent.com/48128550/53677058-ecf1d000-3c88-11e9-8a64-61d27d4e221b.png">
